---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-securely-blocker
data:
  FILE: /opt/securely/blocker-db 
  {{- if .Values.config.securely_blocker }}
  {{- toYaml .Values.config.securely_blocker  | nindent 2}}
  {{- end }}