---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-modsec
data:
  MODSEC_AUDIT_LOG: /opt/securely/modsec_audit.log
  {{- if .Values.config.nginx_modsec }}
  {{- toYaml .Values.config.nginx_modsec | nindent 2}}
  {{- end }}